FROM docker.io/library/golang

WORKDIR /go/src/app
COPY upload-backend upload-backend
COPY protos protos
COPY go.* ./
RUN go get -d app/upload-backend
RUN go install app/upload-backend

ENTRYPOINT ["/go/bin/upload-backend"]
