// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.6.1
// source: protos/download.proto

package protos

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

// when a user requests to download, we'll need the photo_uid to get the full
// picture to the user will need to update metadata accordingly, use
// UpdateMetadataRequest in metadata.proto
type DownloadPhotoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ImgName string `protobuf:"bytes,1,opt,name=img_name,json=imgName,proto3" json:"img_name,omitempty"`
}

func (x *DownloadPhotoRequest) Reset() {
	*x = DownloadPhotoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_download_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DownloadPhotoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadPhotoRequest) ProtoMessage() {}

func (x *DownloadPhotoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_download_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadPhotoRequest.ProtoReflect.Descriptor instead.
func (*DownloadPhotoRequest) Descriptor() ([]byte, []int) {
	return file_protos_download_proto_rawDescGZIP(), []int{0}
}

func (x *DownloadPhotoRequest) GetImgName() string {
	if x != nil {
		return x.ImgName
	}
	return ""
}

type DownloadPhotoResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ImgBlob []byte `protobuf:"bytes,1,opt,name=img_blob,json=imgBlob,proto3" json:"img_blob,omitempty"`
}

func (x *DownloadPhotoResponse) Reset() {
	*x = DownloadPhotoResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_download_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DownloadPhotoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadPhotoResponse) ProtoMessage() {}

func (x *DownloadPhotoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_download_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadPhotoResponse.ProtoReflect.Descriptor instead.
func (*DownloadPhotoResponse) Descriptor() ([]byte, []int) {
	return file_protos_download_proto_rawDescGZIP(), []int{1}
}

func (x *DownloadPhotoResponse) GetImgBlob() []byte {
	if x != nil {
		return x.ImgBlob
	}
	return nil
}

var File_protos_download_proto protoreflect.FileDescriptor

var file_protos_download_proto_rawDesc = []byte{
	0x0a, 0x15, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x64, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61,
	0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x67, 0x72, 0x70, 0x63, 0x22, 0x31, 0x0a,
	0x14, 0x44, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x50, 0x68, 0x6f, 0x74, 0x6f, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x69, 0x6d, 0x67, 0x5f, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x69, 0x6d, 0x67, 0x4e, 0x61, 0x6d, 0x65,
	0x22, 0x32, 0x0a, 0x15, 0x44, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x50, 0x68, 0x6f, 0x74,
	0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x69, 0x6d, 0x67,
	0x5f, 0x62, 0x6c, 0x6f, 0x62, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x69, 0x6d, 0x67,
	0x42, 0x6c, 0x6f, 0x62, 0x32, 0x54, 0x0a, 0x0d, 0x44, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64,
	0x50, 0x68, 0x6f, 0x74, 0x6f, 0x12, 0x43, 0x0a, 0x08, 0x44, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61,
	0x64, 0x12, 0x1a, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x44, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61,
	0x64, 0x50, 0x68, 0x6f, 0x74, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e,
	0x67, 0x72, 0x70, 0x63, 0x2e, 0x44, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x50, 0x68, 0x6f,
	0x74, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x0c, 0x5a, 0x0a, 0x61, 0x70,
	0x70, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protos_download_proto_rawDescOnce sync.Once
	file_protos_download_proto_rawDescData = file_protos_download_proto_rawDesc
)

func file_protos_download_proto_rawDescGZIP() []byte {
	file_protos_download_proto_rawDescOnce.Do(func() {
		file_protos_download_proto_rawDescData = protoimpl.X.CompressGZIP(file_protos_download_proto_rawDescData)
	})
	return file_protos_download_proto_rawDescData
}

var file_protos_download_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_protos_download_proto_goTypes = []interface{}{
	(*DownloadPhotoRequest)(nil),  // 0: grpc.DownloadPhotoRequest
	(*DownloadPhotoResponse)(nil), // 1: grpc.DownloadPhotoResponse
}
var file_protos_download_proto_depIdxs = []int32{
	0, // 0: grpc.DownloadPhoto.Download:input_type -> grpc.DownloadPhotoRequest
	1, // 1: grpc.DownloadPhoto.Download:output_type -> grpc.DownloadPhotoResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protos_download_proto_init() }
func file_protos_download_proto_init() {
	if File_protos_download_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protos_download_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DownloadPhotoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_download_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DownloadPhotoResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protos_download_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protos_download_proto_goTypes,
		DependencyIndexes: file_protos_download_proto_depIdxs,
		MessageInfos:      file_protos_download_proto_msgTypes,
	}.Build()
	File_protos_download_proto = out.File
	file_protos_download_proto_rawDesc = nil
	file_protos_download_proto_goTypes = nil
	file_protos_download_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// DownloadPhotoClient is the client API for DownloadPhoto service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DownloadPhotoClient interface {
	//
	// RPC for download a photo
	Download(ctx context.Context, in *DownloadPhotoRequest, opts ...grpc.CallOption) (*DownloadPhotoResponse, error)
}

type downloadPhotoClient struct {
	cc grpc.ClientConnInterface
}

func NewDownloadPhotoClient(cc grpc.ClientConnInterface) DownloadPhotoClient {
	return &downloadPhotoClient{cc}
}

func (c *downloadPhotoClient) Download(ctx context.Context, in *DownloadPhotoRequest, opts ...grpc.CallOption) (*DownloadPhotoResponse, error) {
	out := new(DownloadPhotoResponse)
	err := c.cc.Invoke(ctx, "/grpc.DownloadPhoto/Download", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DownloadPhotoServer is the server API for DownloadPhoto service.
type DownloadPhotoServer interface {
	//
	// RPC for download a photo
	Download(context.Context, *DownloadPhotoRequest) (*DownloadPhotoResponse, error)
}

// UnimplementedDownloadPhotoServer can be embedded to have forward compatible implementations.
type UnimplementedDownloadPhotoServer struct {
}

func (*UnimplementedDownloadPhotoServer) Download(context.Context, *DownloadPhotoRequest) (*DownloadPhotoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Download not implemented")
}

func RegisterDownloadPhotoServer(s *grpc.Server, srv DownloadPhotoServer) {
	s.RegisterService(&_DownloadPhoto_serviceDesc, srv)
}

func _DownloadPhoto_Download_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DownloadPhotoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DownloadPhotoServer).Download(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.DownloadPhoto/Download",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DownloadPhotoServer).Download(ctx, req.(*DownloadPhotoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _DownloadPhoto_serviceDesc = grpc.ServiceDesc{
	ServiceName: "grpc.DownloadPhoto",
	HandlerType: (*DownloadPhotoServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Download",
			Handler:    _DownloadPhoto_Download_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protos/download.proto",
}
